# --- HARDWARE GROUPS ---
# We group by CPU/Architecture so we know which packages to install

[mediatek]
router-a ansible_host=192.168.1.1
router-b ansible_host=192.168.1.2

[mediatek:vars]
ansible_user=root
# We installed python3 in openwrt-builder, so Ansible works natively!
ansible_python_interpreter=/usr/bin/python3
# Hardware specific interface names
wan_iface=eth1
lan_iface=eth0

# --- FUTURE EXPANSION ---
# [x86]
# firewall-mini ansible_host=192.168.1.254

# --- LOGICAL GROUPS ---

[routers]
router-a
router-b

[gateways]
router-a

[access_points]
router-b

# --- CONTAINERS ---
# The NixOS LXC container behaves like a separate host
[brains]
nixos-brain ansible_host=192.168.1.5 ansible_user=root